In [1]:
import numpy as np
import os
import pandas as pd
from sentence_transformers import SentenceTransformer, util

from sklearn.metrics.pairwise import cosine_similarity

import csv
import pickle
import time
import faiss

D:\Anaconda\envs\Python38\lib\site-packages\tqdm\auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [2]:
# df = pd.read_csv("final_app_info.csv")
# df.shape

(153930, 27)

In [3]:
# df.to_csv("final_app_info2.csv",encoding='utf-8-sig')

In [5]:
df= pd.read_csv("final_app_info2.csv")

In [8]:
df.head()

,Unnamed: 0,unified_publisher_id,unified_publisher_name,country,app_id,unified_app_id,platform,rank,revenue,download,...,price,global_rating_count,publisher_country,description,category1,category2,category3,category4,category5,category6
0,0,56289c8802ac6486a70013a5,"Facebook, Inc.",US,284882215,55c530a702ac64f9c0002dff,1,0,5.801270e+09,7.317791e+08,...,0.0,4792618.0,US,"Connect with friends, family and people who sh...",6005,NaN,NaN,NaN,NaN,NaN
1,1,56289c8802ac6486a70013a5,"Facebook, Inc.",US,com.facebook.phone,559cd21dc063bdebe300000e,2,0,0.000000e+00,5.655900e+05,...,0.0,8159.0,US,Make your phone smarter with Hello. Built by M...,communication,NaN,NaN,NaN,NaN,NaN
2,2,56289c8802ac6486a70013a5,"Facebook, Inc.",US,com.facebook.pages.app,55c5057102ac64f9c00020d2,2,0,0.000000e+00,6.157330e+07,...,0.0,2097780.0,US,"With Facebook Business Suite (Pages Manager), ...",business,NaN,NaN,NaN,NaN,NaN
3,3,56289c8802ac6486a70013a5,"Facebook, Inc.",US,com.facebook.moments,559cd18ac063bdebe3000007,2,0,0.000000e+00,6.226899e+07,...,0.0,1104344.0,US,Moments is going away soon and will be removed...,photography,NaN,NaN,NaN,NaN,NaN
4,4,56289c8802ac6486a70013a5,"Facebook, Inc.",US,com.facebook.orca,55c501db02ac64f9c0001f52,2,0,1.837992e+09,3.662479e+09,...,0.0,79886314.0,US,"Be together whenever, with our free* all-in-on...",communication,NaN,NaN,NaN,NaN,NaN